### ISSUE TITLE
UUIDWritable uses signed long comparisons

### ISSUE THREAD

**Issue by mjwillson** [ScaleUnlimited/cascading.utils#17]
Just a minor thing I noticed in passing.
This isn't equivalent to sorting the UUIDs as unsigned 128-bit values, which is probably what other tools do / what you'd expect.

Probably makes more sense either to use something like
http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/primitives/UnsignedLong.html#compareTo(com.google.common.primitives.UnsignedLong)
if you're going to represent it as two longs, or to represent it as a big-endian byte array and use something like
http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/primitives/UnsignedBytes.html#lexicographicalComparator()

**Comment by Schmed** [comment]
Hi Matthew,

I had this all coded up and was working on a unit test when I realized that UUID has its own compareTo method, and that its implementation apparently treats the high and low portions as signed quantities.

It seems like UUIDWritable.compareTo ought to behave just like UUID.compareTo, regardless of what other tools do.

Please let me know if I’m missing something,

- Chris

> On Jan 8, 2015, at 7:14 AM, Matthew <notifications@github.com> wrote:
> 
> Just a minor thing I noticed in passing.
> This isn't equivalent to a lexicographical sort on the raw bytes of the UUID, which is probably what other tools do / what you'd expect.
> 
> Probably makes more sense either to use something like
> http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/primitives/UnsignedLong.html#compareTo(com.google.common.primitives.UnsignedLong) <http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/primitives/UnsignedLong.html#compareTo(com.google.common.primitives.UnsignedLong)>
> if you're going to represent it as two longs, or to represent it as a big-endian byte array and use something like
> http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/primitives/UnsignedBytes.html#lexicographicalComparator() <http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/primitives/UnsignedBytes.html#lexicographicalComparator()>
> —
> Reply to this email directly or view it on GitHub <https://github.com/ScaleUnlimited/cascading.utils/issues/17>.
> 

-----------------------------------------
Chris Schneider
http://www.scaleunlimited.com <http://www.scaleunlimited.com/>
custom big data solutions
-----------------------------------------

**Comment by mjwillson** [comment]
Ah OK, fair enough :) That is odd, I guess Java is broken too then. Probably best to be consistent with it though.

Just as a note for anyone else that's interested, the RFC does mandate an unsigned bitwise comparison: http://www.ietf.org/rfc/rfc4122.txt

      UUIDs, as defined in this document, can also be ordered
      lexicographically.  For a pair of UUIDs, the first one follows the
      second if the most significant field in which the UUIDs differ is
      greater for the first UUID.  The second precedes the first if the
      most significant field in which the UUIDs differ is greater for
      the second UUID.

Where it defines all the fields as unsigned ints and orders them most significant first, so equivalent to a 128-bit unsigned int comparison.

**Comment by Schmed** [comment]
Hi Matthew,

You do appear to be correct about the spec, and I have found evidence of others complaining <http://anuff.com/2011/04/javautiluuidcompareto-considered-harmful/> about java.util.UUID.compareTo().

Bummer,

- Chris

> On Jan 9, 2015, at 4:13 AM, Matthew <notifications@github.com> wrote:
> 
> Ah OK, fair enough :) That is odd, I guess Java is broken too then. Probably best to be consistent with it though.
> 
> Just as a note for anyone else that's interested, the RFC does mandate an unsigned bitwise comparison: http://www.ietf.org/rfc/rfc4122.txt <http://www.ietf.org/rfc/rfc4122.txt>
>   UUIDs, as defined in this document, can also be ordered
>   lexicographically.  For a pair of UUIDs, the first one follows the
>   second if the most significant field in which the UUIDs differ is
>   greater for the first UUID.  The second precedes the first if the
>   most significant field in which the UUIDs differ is greater for
>   the second UUID.
> Where it defines all the fields as unsigned ints and orders them most significant first, so equivalent to a 128-bit unsigned int comparison.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/ScaleUnlimited/cascading.utils/issues/17#issuecomment-69327066>.
> 

--------------------------------
Mr. Chris Schneider
TransPac Software, Inc.
--------------------------------
